# Generated by Django 4.1 on 2022-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='typedesc',
            field=models.CharField(max_length=200),
        ),
    ]
