# Generated by Django 3.2.13 on 2022-06-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_category_customer_food_order_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
