# Generated by Django 3.2.13 on 2022-06-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='food',
            new_name='foodcategory',
        ),
    ]
