# Generated by Django 4.1.3 on 2023-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_userinfo_alter_orderinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(default='Nothing mentioned', max_length=500, null=True),
        ),
    ]
