# Generated by Django 3.2.13 on 2022-07-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220626_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='foodtype',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Milk Shake', 'Milk Shake')], max_length=64),
        ),
    ]
