# Generated by Django 4.1.3 on 2023-03-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_orderitem_delete_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='quantity',
            new_name='total_items_qty',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='items',
        ),
    ]
