# Generated by Django 4.1.3 on 2023-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_userinfo_alter_orderinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default='price', max_length=64),
            preserve_default=False,
        ),
    ]
