# Generated by Django 3.2.13 on 2022-07-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
