# Generated by Django 3.2.13 on 2022-07-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220726_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cart'),
        ),
    ]
