# Generated by Django 3.2.13 on 2022-07-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_order_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart'),
        ),
    ]
