# Generated by Django 3.2.13 on 2022-07-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_orderinfo_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.cart'),
        ),
    ]
